version: '3.8'
services:
  backend:
    build: ./backend    # ← Usa el Dockerfile de la carpeta backend
    ports:
      - "3000:3000"

  frontend:
    build: ./frontend   # ← Usa el Dockerfile de la carpeta frontend
    ports:
      - "8080:80"
    depends_on:
      - backend